      apiVersion: v1
      kind: Secret
      metadata:
        name: users-api-secret
      type: Opaque
      data:
Jwt__Issuer: ZmNnLWZhc2Uy
Jwt__Audience: ZmNnLWZhc2Uy
Jwt__Key: c3VwZXItc2VjcmV0LWRlbW8ta2V5LWNoYW5nZS1tZQ==
ConnectionStrings__Default: RGF0YSBTb3VyY2U9L2RhdGEvdXNlcnMtYXBpLmRi
